spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ21ySytNSGVPNkZ4dCtnSGQKQXRrclo1RzgzazBUb3VhYWVRSy80RTdHYXFTaFJBTkNBQVFKRThrb29sTExSWjFTVkdmeGtQMU84QnlTblhRZwpOa1RjamJuSS92Y3c3bTdVc0tMYi9uSVdGN3RLa0hHWE40RzdtL3k5dHNBSU5GZHFtaGJ4NHJ3WQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHVENDQWIrZ0F3SUJBZ0lSQU1HMHZBbkw1Y3NCUDRuVTVDVVI0UGd3Q2dZSUtvWkl6ajBFQXdJd2F6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TQXdIZ1lEVlFRTERCZHFaWEpsYlhsQQplbVZ1WW05dmF5QW9TbVZ5WlcxNUtURW5NQ1VHQTFVRUF3d2ViV3RqWlhKMElHcGxjbVZ0ZVVCNlpXNWliMjlyCklDaEtaWEpsYlhrcE1CNFhEVEkyTURReE5UQTVNelV4TkZvWERUSTRNRGN4TlRBNU16VXhORm93U3pFbk1DVUcKQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScFptbGpZWFJsTVNBd0hnWURWUVFMREJkcQpaWEpsYlhsQWVtVnVZbTl2YXlBb1NtVnlaVzE1S1RCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJBa1R5U2lpVXN0Rm5WSlVaL0dRL1U3d0hKS2RkQ0EyUk55TnVjais5ekR1YnRTd290ditjaFlYdTBxUWNaYzMKZ2J1Yi9MMjJ3QWcwVjJxYUZ2SGl2QmlqWkRCaU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBSwpCZ2dyQmdFRkJRY0RBVEFmQmdOVkhTTUVHREFXZ0JUSmZ6anZTdWluSzEvUUh3YVFaQ2RvQWszMWx6QWFCZ05WCkhSRUVFekFSZ2c5c2IyTmhiQzR3ZUdSaVpTNWtaWFl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnWFJXV01UejUKRjhSK1lvNG1LUDA4TzRnUmhFR2RzZDNUQzZ6UnlYOVRzOU1DSVFEOWU0cjBCRUQwVmN6V3F1N3A2MWNiZU40KwpHQnk5dHE3em5Wci9KUUV4TEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          trustore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHakNDQWNDZ0F3SUJBZ0lSQUpWM3dDOXpvR24zZE80eUpKRXdIbjB3Q2dZSUtvWkl6ajBFQXdJd2F6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TQXdIZ1lEVlFRTERCZHFaWEpsYlhsQQplbVZ1WW05dmF5QW9TbVZ5WlcxNUtURW5NQ1VHQTFVRUF3d2ViV3RqWlhKMElHcGxjbVZ0ZVVCNlpXNWliMjlyCklDaEtaWEpsYlhrcE1CNFhEVEkyTURReE5UQTVNekV6TlZvWERUTTJNRFF4TlRBNU16RXpOVm93YXpFZU1Cd0cKQTFVRUNoTVZiV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJRU5CTVNBd0hnWURWUVFMREJkcVpYSmxiWGxBZW1WdQpZbTl2YXlBb1NtVnlaVzE1S1RFbk1DVUdBMVVFQXd3ZWJXdGpaWEowSUdwbGNtVnRlVUI2Wlc1aWIyOXJJQ2hLClpYSmxiWGtwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFZDlCQmplT0NtdFVScVRPYVlyeW0KMUp3WUh3MXltUGljL3JOMWh2NEhma1Z2VnpPNTBhUE5WRjRFQWV4VmY2QkVVN3JFTHhTN1dXWStLTnZyenJlMwppcU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0lFTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDQVFBd0hRWURWUjBPCkJCWUVGTWwvT085SzZLY3JYOUFmQnBCa0oyZ0NUZldYTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUZrK2EzM1EKQWozUk1GQVZvMHBPSUFKbFRYRzNFaVBzRzlFdzdiVytnWktXQWlFQW5XM0YvOEhyUXJmWHBjQld0cnRxUmFBYQpjaDFKbUt1c2VLRlBUTG9KK3ZVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  ssl:
    bundle: web
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  # Step 5: End of session cookie configuration